// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STAMVCCRUD.Data;

#nullable disable

namespace STAMVCCRUD.Migrations
{
    [DbContext(typeof(MVCDbContext))]
    partial class MVCDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STAMVCCRUD.Models.Domain.Mahasiswa", b =>
                {
                    b.Property<string>("Nim")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Jenis_Kelamin")
                        .HasColumnType("int");

                    b.Property<string>("Nama_Mhs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tgl_Lahir")
                        .HasColumnType("datetime2");

                    b.HasKey("Nim");

                    b.ToTable("Mahasiswa");
                });
#pragma warning restore 612, 618
        }
    }
}
